/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/ElementUIPro/examples/src/App.vue')['default']
    AppMain: typeof import('./src/components/Layout/AppMain/index.vue')['default']
    Breadcrumb: typeof import('./src/components/Layout/components/Breadcrumb/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    FooterBar: typeof import('./src/components/Layout/FooterBar/index.vue')['default']
    Hamburger: typeof import('./src/components/Layout/components/Hamburger/index.vue')['default']
    Header: typeof import('./src/components/Layout/Header/index.vue')['default']
    HeaderMenu: typeof import('./src/components/Layout/Menu/HeaderMenu/index.vue')['default']
    HelloWorld: typeof import('./src/components/ElementUIPro/examples/src/components/HelloWorld.vue')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    Layout: typeof import('./src/components/Layout/index.vue')['default']
    Link: typeof import('./src/components/Layout/components/Link/index.vue')['default']
    Logo: typeof import('./src/components/Layout/Logo/index.vue')['default']
    MenuTitle: typeof import('./src/components/Layout/Menu/SideMenu/MenuTitle.vue')['default']
    NavRight: typeof import('./src/components/Layout/NavRight/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPane: typeof import('./src/components/Layout/components/ScrollPane/index.vue')['default']
    Settings: typeof import('./src/components/Layout/Settings/index.vue')['default']
    SideMenu: typeof import('./src/components/Layout/Menu/SideMenu/index.vue')['default']
    SubMenu: typeof import('./src/components/Layout/Menu/HeaderMenu/SubMenu.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TagsMenu: typeof import('./src/components/Layout/components/TagsMenu/index.vue')['default']
    UserInfo: typeof import('./src/components/Layout/components/UserInfo/index.vue')['default']
  }
}
