/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    App: typeof import('./src/components/ElementUIPro/examples/src/App.vue')['default']
    AppMain: typeof import('./src/components/Layout/AppMain/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    FooterBar: typeof import('./src/components/Layout/FooterBar/index.vue')['default']
    HeaderMenu: typeof import('./src/components/Layout/Menu/HeaderMenu/index.vue')['default']
    HelloWorld: typeof import('./src/components/ElementUIPro/examples/src/components/HelloWorld.vue')['default']
    IEpSearch: typeof import('~icons/ep/search')['default']
    Link: typeof import('./src/components/Layout/components/Link/index.vue')['default']
    Logo: typeof import('./src/components/Layout/components/Logo/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPane: typeof import('./src/components/Layout/components/ScrollPane/index.vue')['default']
    Settings: typeof import('./src/components/Layout/Settings/index.vue')['default']
    SideMenu: typeof import('./src/components/Layout/Menu/SideMenu/index.vue')['default']
    TagsMenu: typeof import('./src/components/Layout/Menu/TagsMenu/index.vue')['default']
  }
}
