/*
 vite、rollup、typescript、eslint、prettierrc、
	typescript-eslint/eslint-plugin、typescript-eslint/parser、
	eslint-config-prettier、eslint-plugin-prettier、eslint-plugin-vue、
	vitejs/plugin-legacy、vitejs/plugin-vue、vitejs/plugin-vue-jsx、
	lodash、husky、fast-glob、futil-js、rollup-plugin-terser、rollup-plugin-visualizer、
	unocss、unplugin-auto-import、unplugin-icons、unplugin-svg-component、
	unplugin-vue-components、vite-plugin-svg-icons、
	vite-plugin-restart、vite-plugin-compression、vue-tsc
*/ 